import './globals.css';
import React from 'react';
import StoreProvider from '@/src/app/StoreProvider';
import NavBarContainer from '@/src/app/NavBarContainer';

/* export const metadata: Metadata = {
  title: 'Zebrands test app',
  description: 'Generated by create next app',
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full  bg-gray-100">
      <body className="h-full">
        <StoreProvider>
          <NavBarContainer>
            {children}
          </NavBarContainer>
        </StoreProvider>
      </body>
    </html>
  );
}
